name: Release-plz

on:
  push:
    branches:
      - develop

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Run release-plz
        uses: release-plz/action@992a2096d331cb2c54369732bcefacc8ad05ac08 # v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
